python test.py --task imdb --model bert-base-uncased --dataset imdb
python test.py --task imdb --model bert-base-cased --dataset imdb
python test.py --task imdb --model roberta-base --dataset imdb
python test.py --task imdb --model xlnet-base-cased --dataset imdb
python test.py --task imdb --model albert-base-v2 --dataset imdb
python test.py --task imdb --model microsoft/mpnet-base --dataset imdb
python test.py --task imdb --model microsoft/deberta-base --dataset imdb
python test.py --task imdb --model google/electra-base-generator --dataset imdb
python test.py --task imdb --model facebook/muppet-roberta-base --dataset imdb
